require 'fileutils'

# Options
working_dir = '.'
output_dir = ''
romlist = false
inc_clones = false
dry_run = false
# Variables
rom_count = 0
rom_total = 0
roms_found = {}
missing = []
# Const
RX_EXT_ZIP = /\.zip$/
HELP = <<eof
Move ROMs 1.0
-------------
Moves zipped ROMs files from the target dir to the specified output directory, given a ROM list generated by roms_filter.rb or arcade_roms_filter.rb.

Usage:
    ruby move_roms.rb [romlist] -t [targetdir] [-o [outputdir] -c -d]
    
Arguments:
    romlist Source file with the ROMs
    -t  Target dir with the zipped ROMs
    -o  Output dir were to move the ROMs found at romlist
    -c  Include clones
    -d  Dry run mode (any file is moved)
    -h  Display this help
eof

unless ARGV.empty?
  ARGV.each_with_index { |item, i|
    if item == "-t"
      working_dir = ARGV[i+1]
    elsif item == "-o"
      output_dir = ARGV[i+1]
    elsif item == "-c"
      inc_clones = true
    elsif item == "-d"
      dry_run = true
    elsif item == "-h"
      puts HELP
      exit
    else
      if !romlist && File.exists?(item) && !File.directory?(item)
        romlist = item
      end
    end
  }
end

if !romlist || !File.directory?(working_dir)
  puts HELP
  exit
end

if output_dir == ''
  output_dir = File.join(working_dir, 'moved')
end

unless File.directory? output_dir
  Dir.mkdir output_dir
end

File.open(romlist, "rt") do |f|
  f.each_line do |line|
    roms = []
    rom = line.rstrip
    if inc_clones
      Dir.chdir(working_dir) do
        Dir.glob(rom+"*.zip") do |r|
          next if roms_found[r]
          roms.push r
          roms_found[r] = true
        end
      end
    end
    rom += '.zip' unless RX_EXT_ZIP =~ rom
    roms.push rom
    roms.each do |r|
      rom_total += 1
      romfile = File.join(working_dir, r)
      if File.exists? romfile
        rom_count += 1
        puts r
        unless dry_run
          FileUtils.mv(romfile, File.join(output_dir, r))
        end
      else
        puts "Rom not found: #{r}"
        missing.push(rom)
      end
    end
  end
  puts "\nMoved #{rom_count}/#{rom_total} roms"
  if missing.length > 0
    puts "#{missing.length} rom(s) not found: " + missing.join(", ")
  end
end
# File is closed automatically at end of block